config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :feeds do
    resources :episodes do
      get :play
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :feed
  has_many :listens

  after_create_commit { broadcast_prepend_later_to feed, partial: "feeds/episode", locals: { episode: self }, target: "feed-episodes" }
  after_destroy_commit { broadcast_remove_to feed, target: self }
  after_update_commit { broadcast_replace_later_to feed, partial: "feeds/episode", locals: { episode: self }, target: self }
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :episodes, dependent: :destroy
  has_and_belongs_to_many :users

  def self.new_from_url(url)
    feed = Feed.find_or_initialize_by(url:)
    feed.refresh
    feed
  end

  def refresh
    rss = fetch

    self.update(
      name: rss.title.strip,
      image: rss.itunes_image.strip,
      description: rss.description.strip
    )

    rss.entries.reverse.each do |entry|
      episode = Episode.find_or_initialize_by(url: entry.enclosure_url, feed: self)
      episode.update(
        title: entry.title.strip,
        duration: entry.itunes_duration.strip,
        published_at: entry.published,
        description: entry.summary.strip,
        mimetype: entry.enclosure_type.strip,
        bytes: Integer(entry.enclosure_length, exception: false),
        guid: entry.entry_id.strip,
        image: entry.itunes_image.strip
      )
    end
  end

  def subscribed?(user)
    users.include?(user)
  end

  private

  def fetch
    Feedjira.parse(HTTParty.get(url).body)
  end
end

app/models/listen.rb
class Listen < ApplicationRecord
  belongs_to :user
  belongs_to :episode
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :feeds
  has_many :listens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :authenticate_user!

  def show
    @episode = Episode.includes(:feed).find_by(id: params[:id], feed_id: params[:feed_id])
    @feed = @episode.feed
    # render partial: 'audio_player' if turbo_frame_request?
  end

  def play
    @episode = Episode.includes(:feed).find_by(id: params[:episode_id], feed_id: params[:feed_id])
    @feed = @episode.feed
    render 'audio_player'
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :authenticate_user!

  def index
    @feeds = Feed.includes(:users).limit(10)
    @subscribed = current_user.feeds.all
  end

  def show
    # @feed = current_user.feeds.includes(:episodes).order('episodes.published_at' => :desc).find(params[:id])
    @feed = Feed.includes(:episodes).order('episodes.published_at' => :desc).find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/episodes/_audio_player.html.haml
= turbo_frame_tag 'audio-frame' do

  %div{ class: 'bg-gradient-to-tr from-white via-zinc-300 to-zinc-100 dark:bg-gradient-to-tl dark:from-zinc-800 dark:via-zinc-900 dark:to-black px-10 py-4' }
    #audio{ data: { controller: 'audio-player', 
                    audio_player_play_class: 'iconoir-play-solid', 
                    audio_player_pause_class: 'iconoir-pause-solid', 
                    audio_player_target: 'playPause' } } 

      = audio_tag @episode.url, preload: 'metadata', controls: false, id: 'audio-source', data: { audio_player_target: 'audioSource', action: 'timeupdate->audio-player#playPositionUpdate loadedmetadata->audio-player#metadata' }

      .flex.flex-row.items-center.space-x-5
        - if @episode.image
          .flex-none 
            .drop-shadow= image_tag @episode.image, class: 'object-scale-down max-h-16'
        .flex-none
          %button{ data: { action: 'click->audio-player#playPause' } }
            %i.play-control.iconoir-play-solid{ data: { audio_player_target: 'playControl' } }
        .flex-1.overflow-hidden
          .flex-col
            .flex-1
              .truncate.text-sm #{@episode.feed.name} &mdash; #{@episode.title}
            .flex-1
              = range_field_tag 'playhead', 0, class: 'w-full h-2 bg-gray-400 rounded-lg appearance-none cursor-pointer dark:bg-gray-700', data: { audio_player_target: 'playHead', action: 'change->audio-player#seek' } 
          .flex-1
            #time.flex-1.text-sm.text-right.numeric-fixed
              %span#position{ data: { audio_player_target: 'position' } } -:-
              \/
              %span#duration{ data: { audio_player_target: 'duration' } } -:-

app/views/episodes/audio_player.html.haml
= turbo_frame_tag 'audio-frame' do

  %div{ class: 'bg-gradient-to-tr from-white via-zinc-300 to-zinc-100 dark:bg-gradient-to-tl dark:from-zinc-800 dark:via-zinc-900 dark:to-black px-10 py-4' }
    #audio{ data: { controller: 'audio-player', 
                    audio_player_play_class: 'iconoir-play-solid', 
                    audio_player_pause_class: 'iconoir-pause-solid', 
                    audio_player_target: 'playPause' } } 

      = audio_tag @episode.url, preload: 'metadata', controls: false, id: 'audio-source', data: { audio_player_target: 'audioSource', action: 'timeupdate->audio-player#playPositionUpdate loadedmetadata->audio-player#metadata' }

      .flex.flex-row.items-center.space-x-5
        - if @episode.image
          .flex-none 
            .drop-shadow= image_tag @episode.image, class: 'object-scale-down max-h-16'
        .flex-none
          %button{ data: { action: 'click->audio-player#playPause' } }
            %i.play-control.iconoir-play-solid{ data: { audio_player_target: 'playControl' } }
        .flex-1.overflow-hidden
          .flex-col
            .flex-1
              .truncate.text-sm #{@episode.feed.name} &mdash; #{@episode.title}
            .flex-1
              = range_field_tag 'playhead', 0, class: 'w-full h-2 bg-gray-400 rounded-lg appearance-none cursor-pointer dark:bg-gray-700', data: { audio_player_target: 'playHead', action: 'change->audio-player#seek' } 
          .flex-1
            #time.flex-1.text-sm.text-right.numeric-fixed
              %span#position{ data: { audio_player_target: 'position' } } -:-
              \/
              %span#duration{ data: { audio_player_target: 'duration' } } -:-

app/views/episodes/show.html.haml
= turbo_frame_tag 'content', data: { turbo_action: 'advance' }  do

  %h1= @episode.title 
  %h2= @episode.published_at.to_formatted_s(:long_ordinal)

  = link_to feed_episode_play_path(@episode.feed, @episode), data: { turbo_frame: 'audio-frame' } do 
    %i.iconoir-play
    play

  .episode-description-container{ data: { controller: 'animator' } }
    .episode-description.h-20.overflow-hidden.tranition-height.duration-1000.ease-in-out.bg-gradient-to-b.from-zinc-900.to-zinc-100.dark:from-zinc-100.dark:to-zinc-900.text-transparent.bg-clip-text{ data: { animator_target: 'animate' } }= simple_format @episode.description
    %button.w-full{ data: { action: 'click->animator#slideDown' } }
      .flex.pb-5.items-center.text-sm
        .flex-grow.border-t.border-orange-200.dark:border-orange-950
        %span.flex-shrink.mx-4.text-orange-300.dark:text-orange-900{ data: { animator_target: 'control' } } more

app/views/feeds/_episode.html.haml
%li{id: dom_id(episode)}=  link_to episode.title, [episode.feed, episode]

app/views/feeds/_feed.html.haml
.relative
  = link_to feed do
    = image_tag feed.image.strip, alt: feed.name, class: 'w-full m-0'
  - if feed.subscribed?(current_user)
    %i.iconoir-heart-solid.absolute.bottom-0.right-0.bg-white.text-red-900.text-xl.rounded-full.p-1
  - else
    %i.iconoir-heart.absolute.bottom-0.right-0.bg-white.text-red-900.text-xl.rounded-full.p-1

app/views/feeds/index.html.haml
= turbo_frame_tag 'content', data: { turbo_action: 'advance' }  do

  %h1
    All podcasts 

  .grid.grid-cols-5.gap-2
    = render partial: 'feed', collection: @feeds


  %h1 My podcasts
  %ul 
    - @subscribed.each do |f| 
      %li 
        = link_to f.name, feed_path(f)

app/views/feeds/show.html.haml
= turbo_stream_from @feed

= turbo_frame_tag 'content', data: { turbo_action: :advance } do
  %h1
    = image_tag @feed.image
    = @feed.name

  = simple_format @feed.description

  %ul#feed-episodes
    = render partial: "episode", collection: @feed.episodes

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GloriousRadio
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = stylesheet_link_tag "https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css"
    = javascript_importmap_tags
    = yield :head
  %body.min-h-screen.bg-zinc-100.dark:bg-zinc-900
    %main.prose.prose-zinc.mx-auto.pt-28.px-5.dark:prose-invert.pb-36
      = yield
    %footer
      .fixed.bottom-0.left-0.right-0.px-0.bg-zinc-100.dark:bg-zinc-900.text-zinc-900.dark:text-zinc-200
        = turbo_frame_tag 'audio-frame', data: { turbo_permanent: true }

app/views/welcome/index.html.haml
- content_for :head do 
  = javascript_import_module_tag "pulse-text"

.masthead.flex.items-center.justify-center.max-h-full
  %h1.text-3xl
    Glorious radio